### PR TITLE
overlay: Add remote Google backup provider.

### PR DESCRIPTION
**Pull request by DirtyJerz**
Fixes backup restore failures in the setup wizard.

### CODE REVIEW

**Comment by AlmightyMegadeth00** [comment]
@nuclearmistake didn't you revert this from our vendor overlays?

**Comment by nuclearmistake** [comment]
https://github.com/VanirAOSP/vendor_vanir/blob/L5/overlay/common/frameworks/base/packages/SettingsProvider/res/values/defaults.xml

No, Dave. SOMEone changed the value in FB. I reverted that.

**Comment by AlmightyMegadeth00** [comment]
ok.. well.. why didn't you resubmit it to the vendor overlays then after you reverted it?

**Comment by DirtyJerz** [comment]
took a look inside SettingsProvider.apk and you're right, it is there. It may be the wizard in the gapps package then. I'll factory reset and try another version to confirm. Thanks!

PS For future reference, are github pull-requests a valid way of submitting changes or should everything go through your gerrit?

**Comment by DirtyJerz** [comment]
Yes, It was the gapps, thanks.

**Comment by nuclearmistake** [comment]
Dave, it's IN the vendor overlay.

**Comment by AlmightyMegadeth00** [comment]
case closed.  thanks for letting me harass you nuke :D

**Comment by AlmightyMegadeth00** [comment]
@DirtyJerz  we would prefer you went through our gerrit.  pull requests are acceptable in certain circumstances but please try to use gerrit.  push to port 29419 and HEAD:refs/for/L5.

**Comment by DirtyJerz** [comment]
Thank you.

**Comment by nuclearmistake** [comment]
@Dave Lol letting you harass me? I was just letting you be incorrect. :-P

@DirtyJerz The repo start and repo upload workflow is cleaner and less likely to make you afraid of syncing like Dave used to be. http://gerrit.vanir.co:8080

**Comment by AlmightyMegadeth00** [comment]
Everybody is a little nervous their first time lol

**Comment by DirtyJerz** [comment]
Thanks for the repo start/upload pointers. Looks like some great integration. One question though (ot). How do I build for multiple in my tree? Just keep one manifest and lunch one at a time? or is there another feature of repo/other that I don't know of yet. Specifically, if I want to build AOSP for my tuna and flo devices and vanir for vs985 and vk810.

PS you guys are awesome. Rock on.

**Comment by DHOMD** [comment]
your best of using different folders for vanir + Aosp

You could potentially git init between the 2, but probably just easier to use 2 folders

**Comment by DirtyJerz** [comment]
yikes, that could get rather large. Maybe I'll just keep another branch of the manifest? and sync when I want to switch. That could end up being a lot of bandwidth but there should be mostly common repo paths. Thanks!

EDIT: Do you guys have an IRC so I don't keep filling this PR comment thread with completely OT? I appreciate everything so far.

**Comment by DHOMD** [comment]
We mostly gave up on IRC

Google +
https://plus.google.com/u/0/communities/111378032131473754160

Or one of our Google hangouts.

**Pull request closed without merging**
